apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: disk-checker
  namespace: blues
  labels:
    app: disk-checker
spec:
  selector:
    matchLabels:
      app: disk-checker
  template:
    metadata:
      labels:
        app: disk-checker
    spec:
      hostPID: true
      hostIPC: true
      hostNetwork: true
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - ip-10-0-42-65.eu-central-1.compute.internal
      containers:
      - resources:
          requests:
            cpu: 0.15
        securityContext:
          privileged: true
        image: ikovnatsky/dust:latest
        imagePullPolicy: Always
        name: disk-checked
        # command: ["/bin/sh"]
        command: ["sleep"]
        # args: ["-c", "dust -p -c -d 7 /host"]
        args: ["infinity"]
        volumeMounts:
        - name: host
          mountPath: "/host"
      volumes:
        - name: host
          hostPath:
            path: "/"
