apiVersion: apps/v1
kind: Deployment
metadata:
  name: failing-deployment
  labels:
    app: failing-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: failing-app
  template:
    metadata:
      labels:
        app: failing-app
    spec:
      containers:
      - name: failing-container
        image: busybox:latest
        command: ["invalid_command"]
        args: ["arg1", "arg2"]
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"
